### ISSUE TITLE
Using prefix prompt with newline config setting just prepends $'\n'

### ISSUE THREAD

**Issue by alittlebitweird** [frmendes/geometry#100] opened 2017-02-01 16:10 UTC
<img width="728" alt="screen shot 2017-02-01 at 11 09 49 am" src="https://cloud.githubusercontent.com/assets/4702409/22514960/fc541b2c-e86e-11e6-9fbf-951746605a97.png">

**Comment by desyncr** [comment] 2017-02-01 16:24
Do you mean that you configure `GEOMETRY_PROMPT_PREFIX` like so:

    GEOMETRY_PROMPT_PREFIX=$'\n'

and it doesn't show up?

**Comment by alittlebitweird** [comment] 2017-02-01 18:44
I mean that I configured it like that and it shows up like in the screenshot. I thought it was supposed to render the prompt on a new line, separate from the path/git information. Instead it displays the quoted code

**Comment by SamuelM333** [comment] 2017-02-01 20:35
I'm having the same problem. I would like to have the path, python env, git info, etc on one line and the geometry symbol with the prompt on the next one.

**Comment by SamuelM333** [comment] 2017-02-01 21:11
I managed to configure the theme with the style I said before. I made a copy of the .zsh file and edited the line 67

Was:

```
PROMPT="$GEOMETRY_PROMPT_PREFIX %${#PROMPT_SYMBOL}{%(?.$GEOMETRY_PROMPT.$GEOMETRY_EXIT_VALUE)%} %F{$GEOMETRY_COLOR_DIR}%3~%f "
```

And I wrote:

```
NEWLINE=$'\n'

PROMPT="$GEOMETRY_PROMPT_PREFIX %F{$GEOMETRY_COLOR_DIR}%3~%f ${NEWLINE} %${#PROMPT_SYMBOL}{%(?.$GEOMETRY_PROMPT.$GEOMETRY_EXIT_VALUE)%} "
```

Result:

![screenshot_2017-02-01_17-09-09](https://cloud.githubusercontent.com/assets/13484197/22526327/3200f0ce-e8a1-11e6-9756-66f67cc0c91e.png)

**Comment by alittlebitweird** [comment] 2017-02-01 21:21
Awesome! How about if I wanted to keep the right side on the same line as the path?

**Comment by SamuelM333** [comment] 2017-02-01 21:26
I'm wondering the same :sweat_smile: I will experiment a little more and post my results

**Comment by desyncr** [comment] 2017-02-02 04:37
From my side configuring `PROMPT_PREFIX` with `$'\n'` seems to work as expected. Be sure you are not quoting it this way: `"$'\n'"`.

We are also working on a suffix configuration that would enable @SamuelM333 setup. We've also plans to make PROMPT more flexible on it's configuration. See https://github.com/frmendes/geometry/issues/51.

**Comment by desyncr** [comment] 2017-02-06 20:44
@alittlebitweird Wondering you show us how you configured geometry in order to produce rendering that way.

**Comment by alittlebitweird** [comment] 2017-02-12 17:17
@desyncr this is what I did: GEOMETRY_PROMPT_PREFIX=$'\n'

**Comment by desyncr** [comment] 2017-02-12 17:27
Applied the same configuration both interactively and in `.zshrc` and both ways worked correctly.

Does the issue still reproduces? Can you share your dotfiles?

**Comment by alittlebitweird** [comment] 2017-02-15 19:01
I ended up doing what @SamuelM333 did and it's working out great for me. Beautiful theme dude!

**Comment by desyncr** [comment] 2017-02-15 20:04
Cool. @alittlebitweird Closing this for now as it seems it was most likely a configuration issue.

**Closed as completed by desyncr** 2017-02-15 20:04 UTC
Labels: bug, can't reproduce

**Comment by mustaqimM** [comment] 2018-11-03 03:41
I'm getting the same problem, if I don't quote it in `"$'\n'"`, it doesn't put a newline, but if I do, it prints like this  
 ```bash
 ▲ ~$'
' 
```

**Comment by ducklin5** [comment] 2019-11-15 01:57
Is this not possible anymore? setting `GEOMETRY_PROMPT_PREFIX=$'\n' ` in .zshrc does nothing

**Comment by jedahan** [comment] 2019-11-15 19:01
The closest I could get with current geometry is
`newline() { echo '\n ' }; GEOMETRY_PROMPT+=(newline)`
This is not ideal because of the extra space needed for some reason

**Comment by jedahan** [comment] 2019-11-15 19:04
Actually figured it out:
```
newline() { echo '\n\r' }
GEOMETRY_PROMPT+=(newline)
```

**Comment by jedahan** [comment] 2019-11-15 19:11
@ducklin5 if you pull the latest mnml branch (haven't cut a release yet), I just added `geometry_newline`. You can get a second line prompt with `GEOMETRY_PROMPT+=(geometry_newline)`, thanks for bringing this to our attention!
