### ISSUE TITLE
command not found: async_flush_jobs

### ISSUE THREAD

**Issue by tomspeak** [frmendes/geometry#154] opened 2017-05-09 09:33 UTC
```shell
λ ~ 
-geometry-async-job:1: command not found: async_flush_jobs
-geometry-async-job:2: command not found: async_job
```

Any ideas? Just updated this morning via antibody, and after each command execution, this is printed.

**Comment by frm** [comment] 2017-05-09 09:40
I use antibody as well and I can reproduce this. It's due to `zsh-async` being a submodule and antibody not installing it by default.

While I check this, you can do
```shell
cd ~/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-fribmendes-SLASH-geometry/
git submodule update --init --recursive
```

It should work afterwards.

Note that the `cd` path is only valid for macOS.

**Comment by tomspeak** [comment] 2017-05-09 09:41
Can confirm this works, for anyone else I had to go to this directory:

```shell
cd ~/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-frmendes-SLASH-geometry
```

**Comment by caarlos0** [comment] 2017-05-09 11:38
Hi, I'm the creator of Antibody.

As a workaround, maybe you can:

```shell
cat <<EOF | antibody bundle
  mafredri/zsh-async
  fribmendes/geometry
EOF
```

Then both bundle and update should work.

**Comment by tomspeak** [comment] 2017-05-09 11:40
Confirmed that this also works. Cheers @caarlos0

**Comment by caarlos0** [comment] 2017-05-09 11:41
Just realized it may not work depending on how you're loading the async plugin inside geometry itself...

**Comment by desyncr** [comment] 2017-05-09 11:46
Sorry my bad. Didn't checked interop with Antibody. Should probably add a FAQ or a install entry.

@caarlos0 It just sources it at geometry's start up.

**Comment by caarlos0** [comment] 2017-05-09 11:52
anyways, I'll make antibody support submodules by default :)

**Comment by caarlos0** [comment] 2017-05-09 11:59
https://github.com/getantibody/antibody/pull/180

**Comment by frm** [comment] 2017-05-09 13:26
Thanks for the fast response @caarlos0!

**Comment by caarlos0** [comment] 2017-05-10 21:22
antibody v3.1.0 is out and should fix this issue :)

**Comment by frm** [comment] 2017-05-10 22:24
Cheers, thanks!

**Closed as completed by frm** 2017-05-10 22:24 UTC
Labels: bug
