### ISSUE TITLE
Virtualenv not showing

### ISSUE THREAD

**Issue by Threynaud** [frmendes/geometry#161] opened 2017-05-22 09:36 UTC
Hi,

First thank you you for this theme, I really love it!!

However I have a problem with the virtualenv plugin that doesn't seem to work at all for me.

I have added the plugin in my `.zshrc` before loading geometry:
```
export GEOMETRY_PROMPT_PLUGINS=(exec_time git jobs virtualenv)
ZSH_THEME="geometry/geometry"
```
Nothing is showing in my terminal when a virtualenv is activated:
```
echo $VIRTUAL_ENV
>>> /Users/thms/.virtualenvs/venv_test
```
Doing `export GEOMETRY_PROMPT_PLUGINS=(exec_time git jobs +virtualenv)` displays empty parenthesis where the venv should be showing that the plugin is loaded.

I can't find any setting that could pose a problem..

Thanks for your help!

**Comment by kevin940726** [comment] 2017-05-22 12:41
Maybe not related, but `exec_time` is also broken. Probably related to #160 as I'm pretty sure the problem is in `zsh-async` (I've been able to make it work by reverting it back to v1.0.0).

**Comment by desyncr** [comment] 2017-05-22 13:24
Related to https://github.com/fribmendes/geometry/pull/160

**Comment by desyncr** [comment] 2017-05-26 13:32
@kevin940726 @Threynaud It should be solved in master.

Any feedback is welcome!

**Comment by Threynaud** [comment] 2017-05-26 13:44
Working great indeed, thanks a lot!

**Comment by desyncr** [comment] 2017-05-26 14:16
Awesome! Thanks for reporting.

Closing.

**Closed as completed by desyncr** 2017-05-26 14:16 UTC
Labels: bug
