### ISSUE TITLE
branch parse error

### ISSUE THREAD

**Issue by IanCStewart** [frmendes/geometry#4] opened 2016-05-23 09:19 UTC
I seem ti be getting a parse error when im changing from branch or fetch. This ends up to not showing the branch name in the promt anymore.

_git_branch:4: parse error: condition expected: 1
__gitcomp_nl:compset:5: can only be called from completion function
__gitcomp_nl:compadd:6: can only be called from completion function

![msbzj](https://cloud.githubusercontent.com/assets/14125280/15466061/f5ddf196-20d7-11e6-983f-0e85fe78d120.jpg)
![screen shot 2016-05-23 at 11 17 57](https://cloud.githubusercontent.com/assets/14125280/15466071/095348b6-20d8-11e6-9af9-e51e2409645c.png)

I'm using iTerm on OS X El Capitan v10.11.4

**Comment by frm** [comment] 2016-05-23 10:03
Does the branch have an upstream set?

Also, can you tell me the output of `git rev-parse --short HEAD` and `git symbolic-ref HEAD` when the branch isn't showing?

**Comment by IanCStewart** [comment] 2016-05-23 12:11
Upstream is set. In the pictures you can see what the outputs are

![screen shot 2016-05-23 at 14 06 04](https://cloud.githubusercontent.com/assets/14125280/15470264/e98cb4be-20ef-11e6-8070-a8a58099339b.png)
![screen shot 2016-05-23 at 14 06 15](https://cloud.githubusercontent.com/assets/14125280/15470265/e9932cb8-20ef-11e6-9a67-1bb510ca99f7.png)

**Comment by jmcphers** [comment] 2016-06-07 21:40
I get this constantly, too. 

![image](https://cloud.githubusercontent.com/assets/470418/15875606/ab535386-2cbd-11e6-9530-7690e76ab697.png)

![image](https://cloud.githubusercontent.com/assets/470418/15875620/bc0f37e4-2cbd-11e6-8302-fa690b0aa71d.png)

**Comment by frm** [comment] 2016-06-09 13:25
Sorry for taking so long to answer. I can't seem to reproduce this.

@IanCStewart @jmcphers does any of you have zsh completion installed or enabled?

If so, can you try adding `autoload -U compinit && compinit` to your `.zshrc` and see if it works?

**Comment by frm** [comment] 2016-06-09 13:33
Also, is it possible to get the output of `_git_branch` in the project directory?

**Comment by IanCStewart** [comment] 2016-06-13 06:53
_git_branch gives me the following. I have also put `compinit` in my `.zshrc`.
![screen shot 2016-06-13 at 08 51 41](https://cloud.githubusercontent.com/assets/14125280/15999193/28c5e5ce-3144-11e6-9fc5-57ebb0120c12.png)

**Comment by frm** [comment] 2016-06-14 09:42
@IanCStewart do you have any kind of extra completion enabled or installed? Mainly, for git.

**Comment by IanCStewart** [comment] 2016-06-14 15:26
@frmendes not that im aware of. i just use the basic auto correct that works all over

**Comment by frm** [comment] 2016-06-14 15:53
@IanCStewart I'm really off on this one. Can't seem to find much info or reproduce the issue... It's probably some external configuration messing with it. What's the zsh version you are using?

**Comment by IanCStewart** [comment] 2016-06-17 14:27
@frmendes zsh version 5.0.8

**Comment by frm** [comment] 2016-07-15 15:36
I was **finally** able to reproduce the issue. I just pushed a version that should fix this.

Sorry for taking me so long. Can you confirm everything is good on your end? @IanCStewart @jmcphers

**Comment by frm** [comment] 2016-07-15 17:29
Nevermind that, the problem persists.

**Comment by wwselleck** [comment] 2016-07-17 00:42
I'm getting a ton of errors that I think are coming from you using `'` instead of `"`. Might wanna look into that.

**Comment by frm** [comment] 2016-07-19 23:25
This should be fixed by #5 . I've been using @jedahan 's version for the day and seems to be all good. Can you confirm this, @IanCStewart ?

**Comment by IanCStewart** [comment] 2016-07-21 14:52
@frmendes seems to work fine now! 👌

**Comment by frm** [comment] 2016-07-21 14:54
Cool! Fixed by #5 , thanks to @jedahan

**Closed as completed by frm** 2016-07-21 14:54 UTC
